# Generated by Django 5.2.9 on 2025-12-05 23:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Rutina')),
                ('description', models.TextField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('HYPERTROPHY', 'Hipertrofia'), ('STRENGTH', 'Fuerza'), ('WEIGHT_LOSS', 'Pérdida de Peso'), ('ENDURANCE', 'Resistencia'), ('MAINTENANCE', 'Mantenimiento')], default='HYPERTROPHY', max_length=20, verbose_name='Objetivo de la Rutina')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Entrenamiento')),
                ('day_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('routines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='routines.routine')),
            ],
            options={
                'ordering': ['day_order'],
                'unique_together': {('routines', 'day_order')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden en la sesión')),
                ('sets', models.PositiveIntegerField(default=4, verbose_name='Series')),
                ('reps_min', models.PositiveIntegerField(default=8, verbose_name='Reps Mínimas')),
                ('reps_max', models.PositiveIntegerField(default=12, verbose_name='Reps Máximas')),
                ('rest_time', models.PositiveIntegerField(default=60, verbose_name='Descanso (segundos)')),
                ('notes', models.CharField(blank=True, help_text="Ej: 'Bajar lento', 'Aguantar 1 seg arriba'", max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.workout')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout', 'order')},
            },
        ),
    ]
