# Generated by Django 5.2.9 on 2025-12-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='routines',
            new_name='routine',
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('routine', 'day_order')},
        ),
    ]
