# Generated by Django 5.2.9 on 2025-12-05 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('duration', models.DurationField(verbose_name='Duración')),
                ('notes', models.TextField(blank=True, help_text='Ej: Me sentí cansado, dormí mal anoche.', verbose_name='Notas de la sesión')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='routines.workout')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(verbose_name='# Serie')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('reps', models.PositiveIntegerField(verbose_name='Repeticiones')),
                ('rpe', models.PositiveIntegerField(blank=True, null=True, verbose_name='RPE (1-10)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='training.workoutsession')),
            ],
            options={
                'verbose_name': 'Registro de Serie',
                'verbose_name_plural': 'Registros de Series',
                'ordering': ['set_number'],
            },
        ),
    ]
