# Generated by Django 5.2.9 on 2025-12-05 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Pecho'), ('BACK', 'Espalda'), ('LEGS', 'Piernas'), ('SHOULDERS', 'Hombros'), ('ARMS', 'Brazos'), ('ABS', 'Abdominales'), ('FULL_BODY', 'Cuerpo Completo'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('equipment_type', models.CharField(choices=[('DUMBBELL', 'Mancuernas'), ('BARBELL', 'Barra'), ('MACHINE', 'Máquina'), ('BODYWEIGHT', 'Peso Corporal'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('exercise_type', models.CharField(choices=[('STRENGTH', 'Fuerza'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexibilidad'), ('BALANCE', 'Equilibrio'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
            ],
        ),
    ]
